databases:
  - name: 'dpg-cpottvrv2p9s73eothn0-a'
    databaseName: 'gpt_to_tg'
    user: 'gpt_to_tg_user'
    plan: free

services:
  - type: web
    name: 'dpg-cpottvrv2p9s73eothn0-a'
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 'dpg-cpottvrv2p9s73eothn0-a'
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default